### ISSUE TITLE
What the plugin really is?

### ISSUE THREAD

**Issue by code-roamer** [unitycoder/VelodyneLidarViewer#2]
It is LiDAR Simulator using unity3D?
Or It is just a plugin for visualizing the point cloud data from the real Velodyne Lidar?

**Comment by code-roamer** [comment]
Can the asset produce virtual point cloud data?

**Comment by unitycoder** [comment]
Only from real data, plays live data from device or pcap recordings. (added small note on the main page here also).

i guess for simulated lidar inside unity can check:
https://unity.com/solutions/automotive-transportation/autonomous-vehicle-training
https://github.com/ptibom/Lidar-Simulator
https://github.com/vwaurich/VelodyneLidarUnitySimulation

**Comment by code-roamer** [comment]
@unitycoder Thanks. It is very kind of you to recommend some link for simulated lidar.
