### ISSUE TITLE
Working with any 3D Lidar devices?

### ISSUE THREAD

**Issue by hoangminhanhtai** [unitycoder/VelodyneLidarViewer#3]
Hello,
I wonder if this asset plugin works with any 3D lidar device, rather than Velodyne only.
I have Leishen c16 lidar indeeds

**Comment by unitycoder** [comment]
Only velodyne, but i'm interested to add more supported devices. (looking at Ouster lidars first).
If you have the data specs & samples for "Leishen c16" please link here. (so i can have a look later)

**Comment by bjornsyse** [comment]
I'd love to see Ouster support here.

**Comment by unitycoder** [comment]
thanks for the info! please post your device names also, so can focus those first.

**Comment by bjornsyse** [comment]
Great, I'm on Ouster OS0. https://ouster.com/products/scanning-lidar/os0-sensor/

Just bought the plugin and will try with a pcap-file from it. But perhaps that's being to hopeful? Let me know if you need any testing or info.

**Comment by unitycoder** [comment]
yes, that wont work, its different structure/format to velodyne. (and i dont think there are any converters..)
I'll post here when there is some test version or info available.

**Comment by bjornsyse** [comment]
ah, I see. Thanks, much appreciated. Let me know if you need any specs or similar.

**Comment by bjornsyse** [comment]
(Also, URP support would be useful for our needs)

**Comment by unitycoder** [comment]
added separate urp issue here to follow up, it might already mostly work:
https://github.com/unitycoder/VelodyneLidarViewer/issues/4

**Comment by unitycoder** [comment]
Ouster progress,
![lidarpreview](https://user-images.githubusercontent.com/5438317/190228961-7706c95b-54a8-4ddd-9294-f6a673500662.gif)

and info,
https://forum.unity.com/threads/velodyne-lidar-viewer.833557/#post-8440028

**Comment by unitycoder** [comment]
ouster viewer is now live in store
https://assetstore.unity.com/packages/tools/integration/lidar-viewer-tools-for-unity-compatible-with-ouster-243824?aid=1101loGPL
