### ISSUE TITLE
velodyne hdl-32e support?

### ISSUE THREAD

**Issue by energywhoisshe** [unitycoder/VelodyneLidarViewer#7]
Hi, I'm looking for a solution to import projects recorded with velodyne hdl-32e into Unity. 
Does this asset also support this model? If not, do you have an update plan?

**Comment by unitycoder** [comment]
if you have a sample file, i can test whether it works already. (or if you know some online).

**Comment by energywhoisshe** [comment]
**link removed***

Here are some test files recorded by Velodyne HDL-32E.
Check them please. Thanks a lot.

**Comment by unitycoder** [comment]
thanks got the files, ill test.
if you have your own config file, can share that also (if not, ill use the sample config.xml from velodyne site)

**Comment by energywhoisshe** [comment]
I guess I only have the .pcap files. Yes, please.

**Comment by unitycoder** [comment]
Ok, it has model id "33", so its not supported on my current viewer.

but should be easy to add,
if you can email me so i can show few test images.
![image](https://user-images.githubusercontent.com/5438317/223381795-2cdb625f-daaf-4f9b-9588-056fa4ee540e.png)

**Comment by unitycoder** [comment]
Just adding info here also:
Added support for model id 33, will be available in the store on next update.
